name: teju
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  amplitude_flutter: ^3.10.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.0.9
  draggable_home: ^1.0.3
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
